--- 
- name: install and start nginx
  hosts: all
  became: root
  tasks:
  - name: install nginx
     apt:
      name: nginx
      state: present
   - name: start nginx
     service:
      name: nginx
      state: started
